services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    # Generate a self-signed certificate for local.innohassle.ru
    command: /bin/sh -c "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj '/CN=local.innohassle.ru'; nginx -g 'daemon off;'"
    volumes:
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
