name: 🐞 Bug report
description: Report an issue with innohassle.ru
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please fill out the form below to help us understand and reproduce the issue.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Your device (mobile or desktop, OS, browser)
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Screenshots / Additional context
      description: Attach screenshots or screencast and provide any additional information. If you intend to submit a PR for this issue, tell us in the description. Thanks!
    validations:
      required: true
