name: Link issue to InNoHassle project

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add issue to project
    if: github.repository_owner == 'one-zero-eight' # Do not run in forks
    runs-on: ubuntu-latest
    permissions: # Permissions granted to the 'GITHUB_TOKEN'
      contents: read
      issues:
      repository-projects: write
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/one-zero-eight/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}
